"""instructions table

Revision ID: 20d8b6f9fba9
Revises: 38a28d16a88a
Create Date: 2021-03-04 14:10:00.124972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d8b6f9fba9'
down_revision = '38a28d16a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('specification', sa.Text(), nullable=False),
                    sa.Column('step_order', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructions')
    # ### end Alembic commands ###
