"""added favorite column to plate table

Revision ID: 47cafd0db8be
Revises: f885acb562fd
Create Date: 2021-03-17 11:50:21.557317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cafd0db8be'
down_revision = 'f885acb562fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'favorite')
    # ### end Alembic commands ###
