"""removed instructions column

Revision ID: 38a28d16a88a
Revises: 71704a7e0fdb
Create Date: 2021-03-04 14:05:54.215235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a28d16a88a'
down_revision = '71704a7e0fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
