"""ingredients table

Revision ID: 71704a7e0fdb
Revises: 4e5d0143a07c
Create Date: 2021-03-04 13:35:19.401574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71704a7e0fdb'
down_revision = '4e5d0143a07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('measurement_unit',
                              sa.String(50), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    # ### end Alembic commands ###
