"""create plate table

Revision ID: dde5ffb00409
Revises: 72bc36735bc9
Create Date: 2021-03-05 18:47:42.286885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde5ffb00409'
down_revision = '72bc36735bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('carbs_id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.Column('vegetables_id', sa.Integer(), nullable=False),
    sa.Column('dairy_id', sa.Integer(), nullable=False),
    sa.Column('serving', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carbs_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['dairy_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['fruit_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vegetables_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plates')
    # ### end Alembic commands ###
