"""recipe table

Revision ID: 4e5d0143a07c
Revises: ffdc0a98111c
Create Date: 2021-03-04 12:36:13.511917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5d0143a07c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('food_group', sa.String(
                        length=100), nullable=False),
                    sa.Column('instructions', sa.Text(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('unit', sa.String(length=80), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=False),
                    sa.Column('cook_time', sa.Integer(), nullable=False),
                    sa.Column('flavor_type', sa.String(
                        length=100), nullable=False),
                    sa.Column('img_link', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
